# Generated by Django 5.1.4 on 2025-01-28 01:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_category_sku_alter_product_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPresentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('featured_title', models.CharField(blank=True, help_text='Featured title for the sales page', max_length=255, null=True)),
                ('short_description', models.TextField(blank=True, help_text='Short description for previews', null=True)),
                ('featured_image', models.ImageField(blank=True, help_text='Featured image for the main page', null=True, upload_to='products/')),
                ('order', models.IntegerField(default=0, help_text='Order in which the product will appear on the page')),
                ('featured', models.BooleanField(default=False, help_text='Should this product be featured on the main page?')),
                ('publication_date', models.DateTimeField(auto_now_add=True, help_text='Date when the product was published on the page')),
                ('active', models.BooleanField(default=True, help_text='Is this product active?')),
                ('stock', models.IntegerField(default=0, help_text='Stock available for this product')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presentations', to='products.product')),
            ],
            options={
                'verbose_name': 'Product Presentation',
                'verbose_name_plural': 'Product Presentations',
                'ordering': ['order'],
            },
        ),
    ]
