# Generated by Django 5.1.4 on 2025-01-28 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productpresentation'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='productpresentation',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price for this product', max_digits=10, null=True),
        ),
    ]
