# Generated by Django 5.1.4 on 2025-01-28 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_cost_productpresentation_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
