# Generated by Django 5.1.4 on 2025-06-14 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_product_cost_productpresentation_cost_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPresentationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_images/')),
                ('image_type', models.CharField(choices=[('1', 'Main'), ('2', 'Secondary'), ('3', 'Banner')], max_length=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.productpresentation')),
            ],
        ),
    ]
